@startuml
start

:resetContacts();

:Открыть файл;

if (файл не открыт?) then (да)
    :Ошибка;
    stop
endif

while (читать строку)
    :Разбить строку на поля;

    :Создать объект Contact c;
    :Заполнить поля c;

    :contacts[contactsCount] = c;
    :contactsCount++;
endwhile

stop
@enduml
