@startuml 
start

if (contactsCount == 0?) then (да)
  :Вывести "Список пуст";
  stop
endif

while (while i < contactsCount?) is (да)
  if (contacts[i].deleted == false?) then (да)
    :Вывести contacts[i];
  else (нет)
    :Пропустить удаленный контакт;
  endif
  :i = i + 1;
endwhile (нет)

stop
@enduml
